-- Create standard Aranceles table for VitaFinance
create table if not exists public.vf_aranceles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    price numeric default 0,
    description text,
    active boolean default true
);
-- Enable RLS
alter table public.vf_aranceles enable row level security;
-- Policy (Open access for prototype, can be restricted later)
create policy "Enable read access for all users" on public.vf_aranceles for
select using (true);
create policy "Enable insert for all users" on public.vf_aranceles for
insert with check (true);
create policy "Enable update for all users" on public.vf_aranceles for
update using (true);
create policy "Enable delete for all users" on public.vf_aranceles for delete using (true);