-- Create table for Standard Supply Costs (Costo Estándar de Insumos)
CREATE TABLE IF NOT EXISTS vf_treatment_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_name TEXT NOT NULL UNIQUE,
    -- Link to External App
    category_group TEXT NOT NULL,
    -- '🟢 PREVENTIVOS', '🟡 RESTAURATIVOS', etc.
    supply_cost DECIMAL(10, 2) DEFAULT 0,
    -- Costo Insumos ($2.50, etc)
    duration_override INT DEFAULT NULL,
    -- Optional: Override external duration if needed
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Create table for Global Clinic Configuration (Overhead/Fixed Costs)
CREATE TABLE IF NOT EXISTS vf_clinic_config (
    key TEXT PRIMARY KEY,
    -- 'FIXED_COSTS_MONTHLY', 'OPERATIONAL_HOURS_MONTHLY'
    value DECIMAL(10, 2) NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Insert Default Config (Estimates)
INSERT INTO vf_clinic_config (key, value, description)
VALUES (
        'FIXED_COSTS_MONTHLY',
        1500.00,
        'Gastos Fijos Totales (Alquiler, Luz, Agua, Internet, Sueldos Fijos)'
    ),
    (
        'OPERATIONAL_HOURS_MONTHLY',
        160.00,
        'Horas operativas al mes (ej: 8h x 20 días)'
    ) ON CONFLICT (key) DO NOTHING;
-- Insert Data based on User's List
-- Note: We use ON CONFLICT to update if exists
INSERT INTO vf_treatment_costs (
        treatment_name,
        category_group,
        supply_cost,
        duration_override
    )
VALUES -- 🟢 PREVENTIVOS / BÁSICOS
    ('PROFILAXIS', '🟢 PREVENTIVO', 2.50, 30),
    ('PROFILAXIS NIÑOS', '🟢 PREVENTIVO', 2.00, 25),
    ('SELLANTES', '🟢 PREVENTIVO', 2.20, 30),
    -- 🟡 RESTAURATIVOS
    (
        'RESTAURACIÓN SIMPLE',
        '🟡 RESTAURATIVO',
        3.00,
        30
    ),
    (
        'RESTAURACIÓN COMPUESTA',
        '🟡 RESTAURATIVO',
        4.00,
        40
    ),
    (
        'RESTAURACIÓN COMPLEJA',
        '🟡 RESTAURATIVO',
        5.50,
        60
    ),
    -- 🔶 ESTÉTICA (Mixed into Restaurativo/Estética in list)
    (
        'CARILLA RESINA (x pieza)',
        '🔶 ESTÉTICA',
        6.00,
        60
    ),
    ('BORDES INCISALES', '🔶 ESTÉTICA', 0.00, 30),
    -- No price given, assuming low/zero for now or missing
    ('BLANQUEAMIENTO', '🔶 ESTÉTICA', 0.00, 60),
    -- Missing insumo in prompt text, checking image...
    -- Re-reading prompt carefuly:
    -- BLANQUEAMIENTO: Price 130, Arancel 42.90. Insumo ?? (Not in text block fully, inferring or leaving 0 to edit later)
    -- Wait, I will only insert the ones EXPLICITLY listed with Insumo cost in the text block to be safe.
    -- 🔵 ENDODONCIA
    (
        'ENDODONCIA INCISIVO',
        '🔵 ENDODONCIA',
        18.00,
        90
    ),
    (
        'ENDODONCIA MOLARES',
        '🔵 ENDODONCIA',
        22.00,
        120
    ),
    -- 🔴 CIRUGÍA
    ('EXTRACCIÓN SIMPLE', '🔴 CIRUGÍA', 3.00, 30),
    ('CIRUGÍA 3ROS MOLARES', '🔴 CIRUGÍA', 10.00, 90),
    (
        'IMPLANTE (cirugía)',
        '🔴 IMPLANTOLOGÍA',
        250.00,
        120
    ),
    -- Category in list said 'Implantología', grouping color red
    -- 🟣 ORTODONCIA
    (
        'INSTALACIÓN CONVENCIONAL',
        '🟣 ORTODONCIA',
        45.00,
        90
    ),
    ('CONTROL ORTODONCIA', '🟣 ORTODONCIA', 3.00, 20),
    -- 🟠 PRÓTESIS / LABORATORIO
    (
        'CORONA ZIRCONIA',
        '🟠 PRÓTESIS FIJA',
        120.00,
        90
    ),
    -- Insumos/Lab merged
    (
        'PUENTE 3 PIEZAS',
        '🟠 PRÓTESIS FIJA',
        180.00,
        120
    ),
    -- Lab cost
    -- 🔶 ESTÉTICA FACIAL
    (
        'BOTOX BRUXISMO',
        '🔶 ESTÉTICA FACIAL',
        90.00,
        30
    ),
    (
        'ÁCIDO HIALURÓNICO LABIOS',
        '🔶 ESTÉTICA FACIAL',
        110.00,
        40
    ),
    ('BOTOX PERIORAL', '🔶 ESTÉTICA FACIAL', 0.00, 30),
    -- Insumo missing in text block, leaving 0
    (
        'BIOESTIMULADOR (Radiex)',
        '🔶 ESTÉTICA FACIAL',
        0.00,
        60
    ),
    -- Insumo missing
    (
        'BIOESTIMULADOR (Scultra)',
        '🔶 ESTÉTICA FACIAL',
        0.00,
        30
    ),
    -- Insumo missing
    ('APICECTOMIA', '🔴 CIRUGÍA', 0.00, 60) -- Insumo missing
    ON CONFLICT (treatment_name) DO
UPDATE
SET supply_cost = EXCLUDED.supply_cost,
    category_group = EXCLUDED.category_group,
    duration_override = EXCLUDED.duration_override;