-- 🛠️ CREAR TABLAS LOCALES DE VITAFINANCE
-- Necesarias para guardar los Gastos y Categorías (vf_transactions)
-- 1. Tabla de Categorías
create table if not exists "public"."vf_categories" (
    "id" bigint generated by default as identity not null primary key,
    "name" text not null,
    "type" text check (type in ('income', 'expense')),
    "color" text,
    "icon" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. Tabla de Transacciones Locales (Gastos principalmente)
create table if not exists "public"."vf_transactions" (
    "id" bigint generated by default as identity not null primary key,
    "amount" numeric not null,
    "description" text,
    "date" date not null,
    "type" text check (type in ('income', 'expense')),
    "category_id" bigint references "public"."vf_categories"("id"),
    -- Campos Espejo para compatibilidad con DentalFlow
    "patient_name" text,
    "doctor_name" text,
    "treatment_name" text,
    "payment_code" text,
    "status" text default 'PAGADO',
    "method" text default 'Efectivo',
    "balance" numeric default 0,
    "transaction_time" time,
    "issuer_ruc" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 3. Permisos (Importante)
alter table "public"."vf_categories" enable row level security;
alter table "public"."vf_transactions" enable row level security;
create policy "Permitir todo a anon" on "public"."vf_categories" for all using (true);
create policy "Permitir todo a anon" on "public"."vf_transactions" for all using (true);
create policy "Permitir todo a auth" on "public"."vf_categories" for all using (true);
create policy "Permitir todo a auth" on "public"."vf_transactions" for all using (true);
-- 4. Datos Iniciales de Categorías
insert into "public"."vf_categories" (name, type, color, icon)
values ('Materiales', 'expense', 'blue', 'package'),
    ('Laboratorio', 'expense', 'purple', 'flask'),
    ('Mantenimiento', 'expense', 'orange', 'tool'),
    ('Personal', 'expense', 'red', 'users'),
    ('Servicios Básicos', 'expense', 'yellow', 'zap'),
    ('Marketing', 'expense', 'pink', 'megaphone'),
    ('Impuestos', 'expense', 'gray', 'landmark'),
    ('Otros', 'expense', 'slate', 'circle');