-- Create table for Transaction Categories
CREATE TABLE vf_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    color TEXT,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Create table for Transactions (Income/Expenses)
CREATE TABLE vf_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL,
    description TEXT,
    -- Can be used for general description or fallback
    date DATE NOT NULL,
    category_id BIGINT REFERENCES vf_categories(id),
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    -- DentalFlow Specific Fields
    patient_name TEXT,
    doctor_name TEXT,
    treatment_name TEXT,
    -- Specific treatment name
    payment_code TEXT,
    -- e.g., PAG-2026...
    status TEXT DEFAULT 'COMPLETADO',
    -- e.g., CANCELADO, ABONO, PENDIENTE
    method TEXT,
    -- e.g., EFECTIVO, TARJETA, TRANSFERENCIA
    balance DECIMAL(12, 2) DEFAULT 0.00,
    -- Remaining balance (Por Cobrar)
    transaction_time TIME,
    -- Time of transaction
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Insert default categories
INSERT INTO vf_categories (name, type, color, icon)
VALUES ('Consulta', 'income', '#4ADE80', 'Stethoscope'),
    ('Tratamiento', 'income', '#60A5FA', 'Activity'),
    ('Materiales', 'expense', '#F87171', 'Package'),
    ('Servicios', 'expense', '#FBBF24', 'Zap'),
    ('Alquiler', 'expense', '#A78BFA', 'Home'),
    ('Otros', 'expense', '#9CA3AF', 'HelpCircle');